### ISSUE TITLE
Chapter10

### ISSUE THREAD

**Issue by MaciekLeks** [jasebell/mlbook#1]
Dear Jason,

I think you forgot to add sample stockdata.sql, ratingsdata.sql files into  Chapter10 directory.

I would be grateful to supplement this inconvenience. The book is great.

Maciek

**Comment by Madonahs** [comment]
Just to add on, The book is great 💯 , I use Java and this has really helped me. Thank you Jason.

**Comment by rjkrzykowski** [comment]
I was also looking for this. Does anybody have data that I could use?

**Comment by jasebell** [comment]
There is a PopulateStockTable Java file in the Chapter 10 code folder. Not entirely sure how the sql files got left out. 

As for ratings there's another Java file `https://github.com/jasebell/RecommenderDemo/blob/master/src/uk/co/dataissexy/mahout/PopData.java` that would do the basic job, it's what the chapter was based on, you will need to add the create date though. 

Sorry about the confusion. 
Jason

**Comment by jasebell** [comment]
Thanks for the kind comments, really appreciated. J

**Comment by jasebell** [comment]
Closing this issue.
