### ISSUE TITLE
couldn't find python code in this git

### ISSUE THREAD

**Issue by wahengchang** [jasebell/mlbook#2]
hi Jasebell , thanks for writting the great book. 
I am trying to run the example on the book, as the book states all the source code can be found in this git, but it does not appear python code here

thank you

**Comment by jasebell** [comment]
Hi there, 

The code examples are in Java, Scala for the Spark chapter and R for the chapter on R. I'm looking at porting some of the examples in the future but nothing is planned at the moment. 

Kind regards
Jason
